/**
 * MediCare Connect - DICOM Header & Metadata Tag Dictionary
 * Standards: DICOM (Digital Imaging and Communications in Medicine) PS 3.6 Standard
 */

export interface DICOMTagInfo {
  tag: string;
  name: string;
  vr: string; // Value Representation (UI, SH, LO, DA, TM, CS, PN, DS, IS)
  vm: string;
  description: string;
}

export class DICOMMetadataParser {
  private static readonly tagDictionary: Map<string, DICOMTagInfo> = new Map([
    ['(0008,0016)', { tag: '(0008,0016)', name: 'SOPClassUID', vr: 'UI', vm: '1', description: 'Unique identifier for the SOP Class' }],
    ['(0008,0018)', { tag: '(0008,0018)', name: 'SOPInstanceUID', vr: 'UI', vm: '1', description: 'Unique identifier for the SOP Instance' }],
    ['(0008,0020)', { tag: '(0008,0020)', name: 'StudyDate', vr: 'DA', vm: '1', description: 'Date the acquisition of study started' }],
    ['(0008,0030)', { tag: '(0008,0030)', name: 'StudyTime', vr: 'TM', vm: '1', description: 'Time the acquisition of study started' }],
    ['(0008,0050)', { tag: '(0008,0050)', name: 'AccessionNumber', vr: 'SH', vm: '1', description: 'Order number generated by RIS' }],
    ['(0008,0060)', { tag: '(0008,0060)', name: 'Modality', vr: 'CS', vm: '1', description: 'Type of equipment (CR, CT, MR, NM, US, XA)' }],
    ['(0008,0070)', { tag: '(0008,0070)', name: 'Manufacturer', vr: 'LO', vm: '1', description: 'Manufacturer of the equipment' }],
    ['(0008,1030)', { tag: '(0008,1030)', name: 'StudyDescription', vr: 'LO', vm: '1', description: 'Institution-generated study description' }],
    ['(0010,0010)', { tag: '(0010,0010)', name: 'PatientName', vr: 'PN', vm: '1', description: 'Patient full legal name' }],
    ['(0010,0020)', { tag: '(0010,0020)', name: 'PatientID', vr: 'LO', vm: '1', description: 'Primary identifier for patient' }],
    ['(0010,0030)', { tag: '(0010,0030)', name: 'PatientBirthDate', vr: 'DA', vm: '1', description: 'Birth date of the patient' }],
    ['(0010,0040)', { tag: '(0010,0040)', name: 'PatientSex', vr: 'CS', vm: '1', description: 'Sex of the patient (M, F, O)' }],
    ['(0018,0015)', { tag: '(0018,0015)', name: 'BodyPartExamined', vr: 'CS', vm: '1', description: 'Body part examined in this series' }],
    ['(0018,0050)', { tag: '(0018,0050)', name: 'SliceThickness', vr: 'DS', vm: '1', description: 'Nominal slice thickness in mm' }],
    ['(0018,0080)', { tag: '(0018,0080)', name: 'RepetitionTime', vr: 'DS', vm: '1', description: 'MR Repetition Time in ms' }],
    ['(0018,0081)', { tag: '(0018,0081)', name: 'EchoTime', vr: 'DS', vm: '1', description: 'MR Echo Time in ms' }],
    ['(0020,000D)', { tag: '(0020,000D)', name: 'StudyInstanceUID', vr: 'UI', vm: '1', description: 'Unique identifier for the Study' }],
    ['(0020,000E)', { tag: '(0020,000E)', name: 'SeriesInstanceUID', vr: 'UI', vm: '1', description: 'Unique identifier for the Series' }],
    ['(0020,0013)', { tag: '(0020,0013)', name: 'InstanceNumber', vr: 'IS', vm: '1', description: 'Number that identifies this instance' }],
    ['(0028,0010)', { tag: '(0028,0010)', name: 'Rows', vr: 'US', vm: '1', description: 'Number of rows in the image' }],
    ['(0028,0011)', { tag: '(0028,0011)', name: 'Columns', vr: 'US', vm: '1', description: 'Number of columns in the image' }],
  ]);

  public static getTagInfo(tag: string): DICOMTagInfo | undefined {
    return this.tagDictionary.get(tag);
  }

  public static getAllStandardTags(): DICOMTagInfo[] {
    return Array.from(this.tagDictionary.values());
  }
}
