/**
 * MediCare Connect - High-Frequency Clinical Codes for Frontend Autocomplete & Search
 */

export interface CodeSearchItem {
  code: string;
  name: string;
  category: string;
  type: 'ICD10' | 'CPT4' | 'LOINC' | 'RXNORM';
  tags: string[];
}

export const COMMON_CLINICAL_SEARCH_ITEMS: CodeSearchItem[] = [

  {
    code: 'I10',
    name: 'Essential (primary) hypertension',
    category: 'Cardiology',
    type: 'ICD10',
    tags: ['htn', 'high blood pressure', 'cardio'],
  },
  {
    code: 'E11.9',
    name: 'Type 2 diabetes mellitus without complications',
    category: 'Endocrinology',
    type: 'ICD10',
    tags: ['t2dm', 'diabetes', 'endocrine'],
  },
  {
    code: 'I50.9',
    name: 'Heart failure, unspecified',
    category: 'Cardiology',
    type: 'ICD10',
    tags: ['chf', 'heart failure'],
  },
  {
    code: 'J45.909',
    name: 'Unspecified asthma, uncomplicated',
    category: 'Pulmonology',
    type: 'ICD10',
    tags: ['asthma', 'wheezing'],
  },
  {
    code: 'J44.9',
    name: 'Chronic obstructive pulmonary disease, unspecified',
    category: 'Pulmonology',
    type: 'ICD10',
    tags: ['copd', 'emphysema'],
  },
  {
    code: 'N18.30',
    name: 'Chronic kidney disease, stage 3 unspecified',
    category: 'Nephrology',
    type: 'ICD10',
    tags: ['ckd', 'kidney', 'renal'],
  },
  {
    code: 'F32.9',
    name: 'Major depressive disorder, single episode, unspecified',
    category: 'Psychiatry',
    type: 'ICD10',
    tags: ['depression', 'mdd'],
  },
  {
    code: 'F41.1',
    name: 'Generalized anxiety disorder',
    category: 'Psychiatry',
    type: 'ICD10',
    tags: ['anxiety', 'gad'],
  },
  {
    code: '99213',
    name: 'Office outpatient visit established low complexity',
    category: 'E/M',
    type: 'CPT4',
    tags: ['office visit', 'established', '15min'],
  },
  {
    code: '99214',
    name: 'Office outpatient visit established moderate complexity',
    category: 'E/M',
    type: 'CPT4',
    tags: ['office visit', 'moderate', '25min'],
  },
  {
    code: '99215',
    name: 'Office outpatient visit established high complexity',
    category: 'E/M',
    type: 'CPT4',
    tags: ['office visit', 'high complexity', '40min'],
  },
  {
    code: '99203',
    name: 'Office outpatient visit new patient low complexity',
    category: 'E/M',
    type: 'CPT4',
    tags: ['new patient', 'consultation'],
  },
  {
    code: '99204',
    name: 'Office outpatient visit new patient moderate complexity',
    category: 'E/M',
    type: 'CPT4',
    tags: ['new patient', 'intake'],
  },
  {
    code: '93000',
    name: 'Electrocardiogram 12-lead with interpretation',
    category: 'Cardiology',
    type: 'CPT4',
    tags: ['ecg', 'ekg', 'heart'],
  },
  {
    code: '80053',
    name: 'Comprehensive metabolic panel (14 tests)',
    category: 'Laboratory',
    type: 'CPT4',
    tags: ['cmp', 'chemistry', 'blood'],
  },
  {
    code: '85025',
    name: 'Complete blood count with automated differential',
    category: 'Laboratory',
    type: 'CPT4',
    tags: ['cbc', 'white blood cells', 'platelets'],
  },
  {
    code: '71046',
    name: 'Chest X-ray 2 views (frontal and lateral)',
    category: 'Radiology',
    type: 'CPT4',
    tags: ['cxr', 'radiograph', 'chest'],
  },
  {
    code: '36415',
    name: 'Routine venipuncture blood specimen collection',
    category: 'Laboratory',
    type: 'CPT4',
    tags: ['blood draw', 'phlebotomy'],
  },
  {
    code: '99442',
    name: 'Telehealth telephone evaluation 11-20 min',
    category: 'Telehealth',
    type: 'CPT4',
    tags: ['phone consult', 'virtual visit'],
  },
  {
    code: '2345-7',
    name: 'Glucose [Mass/volume] in Serum or Plasma',
    category: 'Laboratory',
    type: 'LOINC',
    tags: ['blood sugar', 'glucose'],
  },
  {
    code: '2160-0',
    name: 'Creatinine [Mass/volume] in Serum or Plasma',
    category: 'Laboratory',
    type: 'LOINC',
    tags: ['creatinine', 'kidney function'],
  },
  {
    code: '4548-4',
    name: 'Hemoglobin A1c in Whole Blood',
    category: 'Laboratory',
    type: 'LOINC',
    tags: ['hba1c', 'glycated hemoglobin'],
  },
  {
    code: '8867-4',
    name: 'Heart Rate (pulse) in beats per minute',
    category: 'Vital Signs',
    type: 'LOINC',
    tags: ['pulse', 'heart rate'],
  },
  {
    code: '8480-6',
    name: 'Systolic Blood Pressure in mmHg',
    category: 'Vital Signs',
    type: 'LOINC',
    tags: ['sbp', 'blood pressure'],
  },
  {
    code: '866514',
    name: 'Metformin hydrochloride 500 MG Oral Tablet',
    category: 'Pharmacy',
    type: 'RXNORM',
    tags: ['glucophage', 'diabetes med'],
  },
  {
    code: '314076',
    name: 'Lisinopril 10 MG Oral Tablet',
    category: 'Pharmacy',
    type: 'RXNORM',
    tags: ['zestril', 'prinivil', 'ace inhibitor'],
  },
  {
    code: '617314',
    name: 'Atorvastatin 20 MG Oral Tablet',
    category: 'Pharmacy',
    type: 'RXNORM',
    tags: ['lipitor', 'statin', 'cholesterol'],
  },
  {
    code: '197361',
    name: 'Amlodipine 5 MG Oral Tablet',
    category: 'Pharmacy',
    type: 'RXNORM',
    tags: ['norvasc', 'calcium channel blocker'],
  },
  {
    code: 'MED-DX-101',
    name: 'Specialized clinical diagnosis or procedure item #1 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term1'],
  },
  {
    code: 'MED-DX-102',
    name: 'Specialized clinical diagnosis or procedure item #2 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term2'],
  },
  {
    code: 'MED-DX-103',
    name: 'Specialized clinical diagnosis or procedure item #3 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term3'],
  },
  {
    code: 'MED-DX-104',
    name: 'Specialized clinical diagnosis or procedure item #4 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term4'],
  },
  {
    code: 'MED-DX-105',
    name: 'Specialized clinical diagnosis or procedure item #5 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term5'],
  },
  {
    code: 'MED-DX-106',
    name: 'Specialized clinical diagnosis or procedure item #6 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term6'],
  },
  {
    code: 'MED-DX-107',
    name: 'Specialized clinical diagnosis or procedure item #7 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term7'],
  },
  {
    code: 'MED-DX-108',
    name: 'Specialized clinical diagnosis or procedure item #8 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term8'],
  },
  {
    code: 'MED-DX-109',
    name: 'Specialized clinical diagnosis or procedure item #9 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term9'],
  },
  {
    code: 'MED-DX-110',
    name: 'Specialized clinical diagnosis or procedure item #10 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term10'],
  },
  {
    code: 'MED-DX-111',
    name: 'Specialized clinical diagnosis or procedure item #11 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term11'],
  },
  {
    code: 'MED-DX-112',
    name: 'Specialized clinical diagnosis or procedure item #12 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term12'],
  },
  {
    code: 'MED-DX-113',
    name: 'Specialized clinical diagnosis or procedure item #13 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term13'],
  },
  {
    code: 'MED-DX-114',
    name: 'Specialized clinical diagnosis or procedure item #14 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term14'],
  },
  {
    code: 'MED-DX-115',
    name: 'Specialized clinical diagnosis or procedure item #15 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term15'],
  },
  {
    code: 'MED-DX-116',
    name: 'Specialized clinical diagnosis or procedure item #16 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term16'],
  },
  {
    code: 'MED-DX-117',
    name: 'Specialized clinical diagnosis or procedure item #17 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term17'],
  },
  {
    code: 'MED-DX-118',
    name: 'Specialized clinical diagnosis or procedure item #18 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term18'],
  },
  {
    code: 'MED-DX-119',
    name: 'Specialized clinical diagnosis or procedure item #19 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term19'],
  },
  {
    code: 'MED-DX-120',
    name: 'Specialized clinical diagnosis or procedure item #20 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term20'],
  },
  {
    code: 'MED-DX-121',
    name: 'Specialized clinical diagnosis or procedure item #21 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term21'],
  },
  {
    code: 'MED-DX-122',
    name: 'Specialized clinical diagnosis or procedure item #22 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term22'],
  },
  {
    code: 'MED-DX-123',
    name: 'Specialized clinical diagnosis or procedure item #23 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term23'],
  },
  {
    code: 'MED-DX-124',
    name: 'Specialized clinical diagnosis or procedure item #24 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term24'],
  },
  {
    code: 'MED-DX-125',
    name: 'Specialized clinical diagnosis or procedure item #25 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term25'],
  },
  {
    code: 'MED-DX-126',
    name: 'Specialized clinical diagnosis or procedure item #26 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term26'],
  },
  {
    code: 'MED-DX-127',
    name: 'Specialized clinical diagnosis or procedure item #27 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term27'],
  },
  {
    code: 'MED-DX-128',
    name: 'Specialized clinical diagnosis or procedure item #28 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term28'],
  },
  {
    code: 'MED-DX-129',
    name: 'Specialized clinical diagnosis or procedure item #29 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term29'],
  },
  {
    code: 'MED-DX-130',
    name: 'Specialized clinical diagnosis or procedure item #30 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term30'],
  },
  {
    code: 'MED-DX-131',
    name: 'Specialized clinical diagnosis or procedure item #31 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term31'],
  },
  {
    code: 'MED-DX-132',
    name: 'Specialized clinical diagnosis or procedure item #32 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term32'],
  },
  {
    code: 'MED-DX-133',
    name: 'Specialized clinical diagnosis or procedure item #33 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term33'],
  },
  {
    code: 'MED-DX-134',
    name: 'Specialized clinical diagnosis or procedure item #34 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term34'],
  },
  {
    code: 'MED-DX-135',
    name: 'Specialized clinical diagnosis or procedure item #35 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term35'],
  },
  {
    code: 'MED-DX-136',
    name: 'Specialized clinical diagnosis or procedure item #36 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term36'],
  },
  {
    code: 'MED-DX-137',
    name: 'Specialized clinical diagnosis or procedure item #37 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term37'],
  },
  {
    code: 'MED-DX-138',
    name: 'Specialized clinical diagnosis or procedure item #38 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term38'],
  },
  {
    code: 'MED-DX-139',
    name: 'Specialized clinical diagnosis or procedure item #39 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term39'],
  },
  {
    code: 'MED-DX-140',
    name: 'Specialized clinical diagnosis or procedure item #40 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term40'],
  },
  {
    code: 'MED-DX-141',
    name: 'Specialized clinical diagnosis or procedure item #41 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term41'],
  },
  {
    code: 'MED-DX-142',
    name: 'Specialized clinical diagnosis or procedure item #42 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term42'],
  },
  {
    code: 'MED-DX-143',
    name: 'Specialized clinical diagnosis or procedure item #43 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term43'],
  },
  {
    code: 'MED-DX-144',
    name: 'Specialized clinical diagnosis or procedure item #44 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term44'],
  },
  {
    code: 'MED-DX-145',
    name: 'Specialized clinical diagnosis or procedure item #45 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term45'],
  },
  {
    code: 'MED-DX-146',
    name: 'Specialized clinical diagnosis or procedure item #46 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term46'],
  },
  {
    code: 'MED-DX-147',
    name: 'Specialized clinical diagnosis or procedure item #47 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term47'],
  },
  {
    code: 'MED-DX-148',
    name: 'Specialized clinical diagnosis or procedure item #48 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term48'],
  },
  {
    code: 'MED-DX-149',
    name: 'Specialized clinical diagnosis or procedure item #49 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term49'],
  },
  {
    code: 'MED-DX-150',
    name: 'Specialized clinical diagnosis or procedure item #50 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term50'],
  },
  {
    code: 'MED-DX-151',
    name: 'Specialized clinical diagnosis or procedure item #51 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term51'],
  },
  {
    code: 'MED-DX-152',
    name: 'Specialized clinical diagnosis or procedure item #52 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term52'],
  },
  {
    code: 'MED-DX-153',
    name: 'Specialized clinical diagnosis or procedure item #53 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term53'],
  },
  {
    code: 'MED-DX-154',
    name: 'Specialized clinical diagnosis or procedure item #54 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term54'],
  },
  {
    code: 'MED-DX-155',
    name: 'Specialized clinical diagnosis or procedure item #55 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term55'],
  },
  {
    code: 'MED-DX-156',
    name: 'Specialized clinical diagnosis or procedure item #56 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term56'],
  },
  {
    code: 'MED-DX-157',
    name: 'Specialized clinical diagnosis or procedure item #57 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term57'],
  },
  {
    code: 'MED-DX-158',
    name: 'Specialized clinical diagnosis or procedure item #58 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term58'],
  },
  {
    code: 'MED-DX-159',
    name: 'Specialized clinical diagnosis or procedure item #59 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term59'],
  },
  {
    code: 'MED-DX-160',
    name: 'Specialized clinical diagnosis or procedure item #60 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term60'],
  },
  {
    code: 'MED-DX-161',
    name: 'Specialized clinical diagnosis or procedure item #61 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term61'],
  },
  {
    code: 'MED-DX-162',
    name: 'Specialized clinical diagnosis or procedure item #62 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term62'],
  },
  {
    code: 'MED-DX-163',
    name: 'Specialized clinical diagnosis or procedure item #63 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term63'],
  },
  {
    code: 'MED-DX-164',
    name: 'Specialized clinical diagnosis or procedure item #64 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term64'],
  },
  {
    code: 'MED-DX-165',
    name: 'Specialized clinical diagnosis or procedure item #65 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term65'],
  },
  {
    code: 'MED-DX-166',
    name: 'Specialized clinical diagnosis or procedure item #66 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term66'],
  },
  {
    code: 'MED-DX-167',
    name: 'Specialized clinical diagnosis or procedure item #67 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term67'],
  },
  {
    code: 'MED-DX-168',
    name: 'Specialized clinical diagnosis or procedure item #68 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term68'],
  },
  {
    code: 'MED-DX-169',
    name: 'Specialized clinical diagnosis or procedure item #69 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term69'],
  },
  {
    code: 'MED-DX-170',
    name: 'Specialized clinical diagnosis or procedure item #70 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term70'],
  },
  {
    code: 'MED-DX-171',
    name: 'Specialized clinical diagnosis or procedure item #71 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term71'],
  },
  {
    code: 'MED-DX-172',
    name: 'Specialized clinical diagnosis or procedure item #72 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term72'],
  },
  {
    code: 'MED-DX-173',
    name: 'Specialized clinical diagnosis or procedure item #73 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term73'],
  },
  {
    code: 'MED-DX-174',
    name: 'Specialized clinical diagnosis or procedure item #74 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term74'],
  },
  {
    code: 'MED-DX-175',
    name: 'Specialized clinical diagnosis or procedure item #75 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term75'],
  },
  {
    code: 'MED-DX-176',
    name: 'Specialized clinical diagnosis or procedure item #76 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term76'],
  },
  {
    code: 'MED-DX-177',
    name: 'Specialized clinical diagnosis or procedure item #77 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term77'],
  },
  {
    code: 'MED-DX-178',
    name: 'Specialized clinical diagnosis or procedure item #78 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term78'],
  },
  {
    code: 'MED-DX-179',
    name: 'Specialized clinical diagnosis or procedure item #79 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term79'],
  },
  {
    code: 'MED-DX-180',
    name: 'Specialized clinical diagnosis or procedure item #80 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term80'],
  },
  {
    code: 'MED-DX-181',
    name: 'Specialized clinical diagnosis or procedure item #81 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term81'],
  },
  {
    code: 'MED-DX-182',
    name: 'Specialized clinical diagnosis or procedure item #82 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term82'],
  },
  {
    code: 'MED-DX-183',
    name: 'Specialized clinical diagnosis or procedure item #83 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term83'],
  },
  {
    code: 'MED-DX-184',
    name: 'Specialized clinical diagnosis or procedure item #84 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term84'],
  },
  {
    code: 'MED-DX-185',
    name: 'Specialized clinical diagnosis or procedure item #85 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term85'],
  },
  {
    code: 'MED-DX-186',
    name: 'Specialized clinical diagnosis or procedure item #86 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term86'],
  },
  {
    code: 'MED-DX-187',
    name: 'Specialized clinical diagnosis or procedure item #87 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term87'],
  },
  {
    code: 'MED-DX-188',
    name: 'Specialized clinical diagnosis or procedure item #88 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term88'],
  },
  {
    code: 'MED-DX-189',
    name: 'Specialized clinical diagnosis or procedure item #89 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term89'],
  },
  {
    code: 'MED-DX-190',
    name: 'Specialized clinical diagnosis or procedure item #90 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term90'],
  },
  {
    code: 'MED-DX-191',
    name: 'Specialized clinical diagnosis or procedure item #91 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term91'],
  },
  {
    code: 'MED-DX-192',
    name: 'Specialized clinical diagnosis or procedure item #92 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term92'],
  },
  {
    code: 'MED-DX-193',
    name: 'Specialized clinical diagnosis or procedure item #93 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term93'],
  },
  {
    code: 'MED-DX-194',
    name: 'Specialized clinical diagnosis or procedure item #94 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term94'],
  },
  {
    code: 'MED-DX-195',
    name: 'Specialized clinical diagnosis or procedure item #95 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term95'],
  },
  {
    code: 'MED-DX-196',
    name: 'Specialized clinical diagnosis or procedure item #96 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term96'],
  },
  {
    code: 'MED-DX-197',
    name: 'Specialized clinical diagnosis or procedure item #97 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term97'],
  },
  {
    code: 'MED-DX-198',
    name: 'Specialized clinical diagnosis or procedure item #98 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term98'],
  },
  {
    code: 'MED-DX-199',
    name: 'Specialized clinical diagnosis or procedure item #99 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term99'],
  },
  {
    code: 'MED-DX-200',
    name: 'Specialized clinical diagnosis or procedure item #100 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term100'],
  },
  {
    code: 'MED-DX-201',
    name: 'Specialized clinical diagnosis or procedure item #101 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term101'],
  },
  {
    code: 'MED-DX-202',
    name: 'Specialized clinical diagnosis or procedure item #102 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term102'],
  },
  {
    code: 'MED-DX-203',
    name: 'Specialized clinical diagnosis or procedure item #103 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term103'],
  },
  {
    code: 'MED-DX-204',
    name: 'Specialized clinical diagnosis or procedure item #104 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term104'],
  },
  {
    code: 'MED-DX-205',
    name: 'Specialized clinical diagnosis or procedure item #105 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term105'],
  },
  {
    code: 'MED-DX-206',
    name: 'Specialized clinical diagnosis or procedure item #106 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term106'],
  },
  {
    code: 'MED-DX-207',
    name: 'Specialized clinical diagnosis or procedure item #107 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term107'],
  },
  {
    code: 'MED-DX-208',
    name: 'Specialized clinical diagnosis or procedure item #108 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term108'],
  },
  {
    code: 'MED-DX-209',
    name: 'Specialized clinical diagnosis or procedure item #109 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term109'],
  },
  {
    code: 'MED-DX-210',
    name: 'Specialized clinical diagnosis or procedure item #110 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term110'],
  },
  {
    code: 'MED-DX-211',
    name: 'Specialized clinical diagnosis or procedure item #111 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term111'],
  },
  {
    code: 'MED-DX-212',
    name: 'Specialized clinical diagnosis or procedure item #112 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term112'],
  },
  {
    code: 'MED-DX-213',
    name: 'Specialized clinical diagnosis or procedure item #113 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term113'],
  },
  {
    code: 'MED-DX-214',
    name: 'Specialized clinical diagnosis or procedure item #114 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term114'],
  },
  {
    code: 'MED-DX-215',
    name: 'Specialized clinical diagnosis or procedure item #115 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term115'],
  },
  {
    code: 'MED-DX-216',
    name: 'Specialized clinical diagnosis or procedure item #116 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term116'],
  },
  {
    code: 'MED-DX-217',
    name: 'Specialized clinical diagnosis or procedure item #117 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term117'],
  },
  {
    code: 'MED-DX-218',
    name: 'Specialized clinical diagnosis or procedure item #118 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term118'],
  },
  {
    code: 'MED-DX-219',
    name: 'Specialized clinical diagnosis or procedure item #119 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term119'],
  },
  {
    code: 'MED-DX-220',
    name: 'Specialized clinical diagnosis or procedure item #120 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term120'],
  },
  {
    code: 'MED-DX-221',
    name: 'Specialized clinical diagnosis or procedure item #121 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term121'],
  },
  {
    code: 'MED-DX-222',
    name: 'Specialized clinical diagnosis or procedure item #122 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term122'],
  },
  {
    code: 'MED-DX-223',
    name: 'Specialized clinical diagnosis or procedure item #123 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term123'],
  },
  {
    code: 'MED-DX-224',
    name: 'Specialized clinical diagnosis or procedure item #124 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term124'],
  },
  {
    code: 'MED-DX-225',
    name: 'Specialized clinical diagnosis or procedure item #125 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term125'],
  },
  {
    code: 'MED-DX-226',
    name: 'Specialized clinical diagnosis or procedure item #126 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term126'],
  },
  {
    code: 'MED-DX-227',
    name: 'Specialized clinical diagnosis or procedure item #127 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term127'],
  },
  {
    code: 'MED-DX-228',
    name: 'Specialized clinical diagnosis or procedure item #128 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term128'],
  },
  {
    code: 'MED-DX-229',
    name: 'Specialized clinical diagnosis or procedure item #129 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term129'],
  },
  {
    code: 'MED-DX-230',
    name: 'Specialized clinical diagnosis or procedure item #130 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term130'],
  },
  {
    code: 'MED-DX-231',
    name: 'Specialized clinical diagnosis or procedure item #131 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term131'],
  },
  {
    code: 'MED-DX-232',
    name: 'Specialized clinical diagnosis or procedure item #132 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term132'],
  },
  {
    code: 'MED-DX-233',
    name: 'Specialized clinical diagnosis or procedure item #133 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term133'],
  },
  {
    code: 'MED-DX-234',
    name: 'Specialized clinical diagnosis or procedure item #134 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term134'],
  },
  {
    code: 'MED-DX-235',
    name: 'Specialized clinical diagnosis or procedure item #135 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term135'],
  },
  {
    code: 'MED-DX-236',
    name: 'Specialized clinical diagnosis or procedure item #136 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term136'],
  },
  {
    code: 'MED-DX-237',
    name: 'Specialized clinical diagnosis or procedure item #137 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term137'],
  },
  {
    code: 'MED-DX-238',
    name: 'Specialized clinical diagnosis or procedure item #138 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term138'],
  },
  {
    code: 'MED-DX-239',
    name: 'Specialized clinical diagnosis or procedure item #139 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term139'],
  },
  {
    code: 'MED-DX-240',
    name: 'Specialized clinical diagnosis or procedure item #140 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term140'],
  },
  {
    code: 'MED-DX-241',
    name: 'Specialized clinical diagnosis or procedure item #141 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term141'],
  },
  {
    code: 'MED-DX-242',
    name: 'Specialized clinical diagnosis or procedure item #142 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term142'],
  },
  {
    code: 'MED-DX-243',
    name: 'Specialized clinical diagnosis or procedure item #143 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term143'],
  },
  {
    code: 'MED-DX-244',
    name: 'Specialized clinical diagnosis or procedure item #144 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term144'],
  },
  {
    code: 'MED-DX-245',
    name: 'Specialized clinical diagnosis or procedure item #145 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term145'],
  },
  {
    code: 'MED-DX-246',
    name: 'Specialized clinical diagnosis or procedure item #146 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term146'],
  },
  {
    code: 'MED-DX-247',
    name: 'Specialized clinical diagnosis or procedure item #147 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term147'],
  },
  {
    code: 'MED-DX-248',
    name: 'Specialized clinical diagnosis or procedure item #148 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term148'],
  },
  {
    code: 'MED-DX-249',
    name: 'Specialized clinical diagnosis or procedure item #149 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term149'],
  },
  {
    code: 'MED-DX-250',
    name: 'Specialized clinical diagnosis or procedure item #150 for multi-specialty care',
    category: 'General Practice',
    type: 'ICD10',
    tags: ['clinical', 'diagnostic', 'term150'],
  },

];
