/**
 * @fileoverview US States constants for the Healthcare Appointment Management System.
 */

export const USStates = [
  { name: 'Alabama', abbreviation: 'AL', timezones: ['America/Chicago'] },
  { name: 'Alaska', abbreviation: 'AK', timezones: ['America/Anchorage', 'America/Adak'] },
  { name: 'Arizona', abbreviation: 'AZ', timezones: ['America/Phoenix'] },
  { name: 'Arkansas', abbreviation: 'AR', timezones: ['America/Chicago'] },
  { name: 'California', abbreviation: 'CA', timezones: ['America/Los_Angeles'] },
  { name: 'Colorado', abbreviation: 'CO', timezones: ['America/Denver'] },
  { name: 'Connecticut', abbreviation: 'CT', timezones: ['America/New_York'] },
  { name: 'Delaware', abbreviation: 'DE', timezones: ['America/New_York'] },
  { name: 'Florida', abbreviation: 'FL', timezones: ['America/New_York', 'America/Chicago'] },
  { name: 'Georgia', abbreviation: 'GA', timezones: ['America/New_York'] },
  { name: 'Hawaii', abbreviation: 'HI', timezones: ['Pacific/Honolulu'] },
  { name: 'Idaho', abbreviation: 'ID', timezones: ['America/Boise', 'America/Los_Angeles'] },
  { name: 'Illinois', abbreviation: 'IL', timezones: ['America/Chicago'] },
  { name: 'Indiana', abbreviation: 'IN', timezones: ['America/Indiana/Indianapolis', 'America/Chicago'] },
  { name: 'Iowa', abbreviation: 'IA', timezones: ['America/Chicago'] },
  { name: 'Kansas', abbreviation: 'KS', timezones: ['America/Chicago', 'America/Denver'] },
  { name: 'Kentucky', abbreviation: 'KY', timezones: ['America/New_York', 'America/Chicago'] },
  { name: 'Louisiana', abbreviation: 'LA', timezones: ['America/Chicago'] },
  { name: 'Maine', abbreviation: 'ME', timezones: ['America/New_York'] },
  { name: 'Maryland', abbreviation: 'MD', timezones: ['America/New_York'] },
  { name: 'Massachusetts', abbreviation: 'MA', timezones: ['America/New_York'] },
  { name: 'Michigan', abbreviation: 'MI', timezones: ['America/Detroit', 'America/Menominee'] },
  { name: 'Minnesota', abbreviation: 'MN', timezones: ['America/Chicago'] },
  { name: 'Mississippi', abbreviation: 'MS', timezones: ['America/Chicago'] },
  { name: 'Missouri', abbreviation: 'MO', timezones: ['America/Chicago'] },
  { name: 'Montana', abbreviation: 'MT', timezones: ['America/Denver'] },
  { name: 'Nebraska', abbreviation: 'NE', timezones: ['America/Chicago', 'America/Denver'] },
  { name: 'Nevada', abbreviation: 'NV', timezones: ['America/Los_Angeles'] },
  { name: 'New Hampshire', abbreviation: 'NH', timezones: ['America/New_York'] },
  { name: 'New Jersey', abbreviation: 'NJ', timezones: ['America/New_York'] },
  { name: 'New Mexico', abbreviation: 'NM', timezones: ['America/Denver'] },
  { name: 'New York', abbreviation: 'NY', timezones: ['America/New_York'] },
  { name: 'North Carolina', abbreviation: 'NC', timezones: ['America/New_York'] },
  { name: 'North Dakota', abbreviation: 'ND', timezones: ['America/Chicago', 'America/Denver'] },
  { name: 'Ohio', abbreviation: 'OH', timezones: ['America/New_York'] },
  { name: 'Oklahoma', abbreviation: 'OK', timezones: ['America/Chicago'] },
  { name: 'Oregon', abbreviation: 'OR', timezones: ['America/Los_Angeles', 'America/Boise'] },
  { name: 'Pennsylvania', abbreviation: 'PA', timezones: ['America/New_York'] },
  { name: 'Rhode Island', abbreviation: 'RI', timezones: ['America/New_York'] },
  { name: 'South Carolina', abbreviation: 'SC', timezones: ['America/New_York'] },
  { name: 'South Dakota', abbreviation: 'SD', timezones: ['America/Chicago', 'America/Denver'] },
  { name: 'Tennessee', abbreviation: 'TN', timezones: ['America/Chicago', 'America/New_York'] },
  { name: 'Texas', abbreviation: 'TX', timezones: ['America/Chicago', 'America/Denver'] },
  { name: 'Utah', abbreviation: 'UT', timezones: ['America/Denver'] },
  { name: 'Vermont', abbreviation: 'VT', timezones: ['America/New_York'] },
  { name: 'Virginia', abbreviation: 'VA', timezones: ['America/New_York'] },
  { name: 'Washington', abbreviation: 'WA', timezones: ['America/Los_Angeles'] },
  { name: 'West Virginia', abbreviation: 'WV', timezones: ['America/New_York'] },
  { name: 'Wisconsin', abbreviation: 'WI', timezones: ['America/Chicago'] },
  { name: 'Wyoming', abbreviation: 'WY', timezones: ['America/Denver'] }
];
